In [2]:
import numpy as np
import pandas as pd

In [23]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dogg']
}

In [24]:
df = pd.DataFrame(data)

In [25]:
filter_df = df[df['Category']=='dog']

In [27]:
filter_df

   Numeric1  Numeric2 Category
0       1.0       5.0      dog

In [26]:
filter_df_contains = df[df['Category'].str.contains('do',na=False)]

In [28]:
filter_df_contains

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
3       4.0       8.2     dogg

In [35]:
df = pd.DataFrame({
    'variable':['value1-value2-value3','value4-value5','value6']
})

In [30]:
split_df = df['variable'].str.split('-',expand=True)

In [31]:
split_df.columns = ['var1','var2','var3']

In [32]:
split_df

     var1    var2    var3
0  value1  value2  value3
1  value4  value5     NaN
2  value6     NaN     NaN

In [36]:
df['variable'] = df['variable'].str[0:5] + df['variable'].str[6:12]

In [37]:
df['variable']

0    value-value
1    value-value
2          value
Name: variable, dtype: str

In [42]:
text="apple,"
result=text.rstrip(",")
print(result)

apple

In [43]:
text="banana,,"
result=text.rstrip(",")
print(result)

banana

In [44]:
text=",orange,pear"
result=text.lstrip(",")
print(result)

orange,pear

In [45]:
df =pd.DataFrame({
    "문항1":['1','2',"",'2'],
    "문항2":["",'2','3',""]
})

In [46]:
df["문항"] = df["문항1"].fillna("")+","+df["문항2"].fillna("")

In [50]:
df = df.drop(columns=["문항1","문항2"])

In [51]:
print(df)

    문항
0   1,
1  2,2
2   ,3
3   2,

In [52]:
df =pd.DataFrame({
    "문항1":['1','2',"",'2'],
    "문항2":["",'2','3',""],
    "문항3":["",'1','2',""]
})

In [54]:
#공백 문자열 처리
cols = ["문항1","문항2","문항3"]
df[cols]=df[cols].replace(r'^\s*$','무응답',regex=True)

In [56]:
#문항 합치기
df["문항"]=df["문항1"].fillna("")+","+df["문항2"].fillna("")+","+df["문항3"].fillna("")

In [58]:
print(df)

   문항1  문항2  문항3         문항
0    1  무응답  무응답  1,무응답,무응답
1    2    2    1      2,2,1
2  무응답    3    2    무응답,3,2
3    2  무응답  무응답  2,무응답,무응답

In [68]:
df = pd.DataFrame({
    'variable':['value1-value2-value3',"value3-value1-value5","vvdfvalue165656"]
})

In [69]:
#특정문자가 포함되어 있으면 전체를 해당문자로 변경
df["new_variable"]=df['variable'].str.extract(r'(value1)')

In [70]:
print(df["new_variable"])

0    value1
1    value1
2    value1
Name: new_variable, dtype: str

In [71]:
df = pd.DataFrame({
    'variable':['value1-value2-value3',"value3-value1-value5","vvdfvalue165656"]
})

In [72]:
#특정문자가 포함되어 있으면 전체를 해당문자로 변경
df["new_variable"]=df['variable'].str.extract(r'(value2)')

In [74]:
print(df["new_variable"])

0    value2
1       NaN
2       NaN
Name: new_variable, dtype: str

In [94]:
data = {'date':['202103151345','20210315 1345','0715','07-15','20210315','1']}
df = pd.DataFrame(data)

In [95]:
df['date']=pd.to_datetime(df['date'], format='%Y%m%d %H%M', errors='coerce')

In [97]:
print(df['date'])

0                   NaT
1   2021-03-15 13:45:00
2                   NaT
3                   NaT
4                   NaT
5                   NaT
Name: date, dtype: datetime64[us]

In [ ]:
data = {'date':['202103151345','20210315 1345','0715','07-15','20210315','1']}
df = pd.DataFrame(data)

In [91]:
df['date']=pd.to_datetime(df['date'], format='%H%M', errors='coerce').dt.time #dt.time = 시간을 나타내는거라 구분.

In [90]:
print(df['date'])

0         NaT
1         NaT
2    07:15:00
3         NaT
4         NaT
5         NaT
Name: date, dtype: object

In [99]:
data = {'date':['202103151345','20210315 1345','0715','07-15','20210315','1']}
df = pd.DataFrame(data)

In [101]:
df['date']=pd.to_datetime(df['date'], format='%Y%m%d', errors='coerce')

In [102]:
print(df['date'])

0          NaT
1          NaT
2          NaT
3          NaT
4   2021-03-15
5          NaT
Name: date, dtype: datetime64[us]

In [114]:
data = {'date':['202103151345','20210315 1345','0715','07-15','20210315','1']}
df = pd.DataFrame(data)

In [115]:
df['date']=pd.to_datetime(df['date'], format='%H-%M', errors='coerce').dt.time

In [116]:
print(df['date'])

0         NaT
1         NaT
2         NaT
3    07:15:00
4         NaT
5         NaT
Name: date, dtype: object

In [143]:
data = {'hour':['1','2','12','22','11']}
df = pd.DataFrame(data)

In [144]:
df['hour'].str.rjust(4,fillchar='0')

0    0001
1    0002
2    0012
3    0022
4    0011
Name: hour, dtype: str

In [130]:
data = {'hour':['1','2','12','22','11']}
df = pd.DataFrame(data)

In [135]:
df['hour'].str.ljust(4,fillchar='0')

0    1000
1    2000
2    1200
3    2200
4    1100
Name: hour, dtype: str

In [3]:
data = {'date':['1','2','12','22','11']}
df = pd.DataFrame(data)

In [4]:
df['date'] = pd.to_datetime(df['date'], format='%H%M',errors='coerce').dt.time

In [6]:
print(df['date'])

0         NaT
1         NaT
2    01:02:00
3    02:02:00
4    01:01:00
Name: date, dtype: object

In [149]:
df.to_csv('C:/Users/User/Downloads/실습/new_program.csv',index=False, encoding='UTF-8')